spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    show-sql: false

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
