name: Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      git-sha: ${{ steps.git-sha.outputs.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Git SHA
        id: git-sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  retag:
    needs: vars
    uses: ./.github/workflows/module-docker-retag.yml
    with:
      git-sha: ${{ needs.vars.outputs.git-sha }}
      version: ${{ github.ref_name }}
    secrets: inherit

  deploy:
    needs: retag
    uses: ./.github/workflows/module-deploy.yml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit
